In [ ]:
#Concatenate

In [ ]:
import numpy as np

In [ ]:
#1D array

d=np.arange(1,5)
e=np.arange(1,5)

print(d)
print(e)

[1 2 3 4]
[1 2 3 4]


In [ ]:
print(d.shape)
print(d.ndim)

(4,)
1


In [ ]:
np.concatenate([d,e])

array([1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
np.concatenate([d,e],axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
np.concatenate([d,e],axis=0)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
#2D arrays
d=np.arange(1,5).reshape((1,4))
e=np.arange(1,5).reshape((1,4))

print(d)

print(d.shape)
print(d.ndim)

print(e)

print(e.shape)
print(e.ndim)

[[1 2 3 4]]
(1, 4)
2
[[1 2 3 4]]
(1, 4)
2


In [ ]:
# default axis=0
np.concatenate([d,e])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
np.concatenate([d,e],axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
np.concatenate([d,e],axis=1)

array([[1, 2, 3, 4, 1, 2, 3, 4]])

In [ ]:
# 2D arrays with m rows and n columns
d=np.arange(1,13).reshape((3,4))
e=np.arange(1,13).reshape((3,4))

In [ ]:
np.concatenate([d,e])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.concatenate([d,e],axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.concatenate([d,e],axis=1)

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [ ]:
d=np.arange(1,13).reshape((3,4))
e=np.arange(1,5).reshape((1,4))
print(d)

print(d.shape)
print(d.ndim)
print("-"*50)
print(e)

print(e.shape)
print(e.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
--------------------------------------------------
[[1 2 3 4]]
(1, 4)
2


In [ ]:
np.concatenate([d,e])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
np.concatenate([d,e],axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [ ]:
d=np.arange(1,13).reshape((3,4))
e=np.arange(1,5)
print(d)

print(d.shape)
print(d.ndim)
print("-"*50)
print(e)

print(e.shape)
print(e.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
--------------------------------------------------
[1 2 3 4]
(4,)
1


In [ ]:
np.concatenate([d,e],axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
np.concatenate([d,e],axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
d=np.arange(1,13).reshape((3,4))
e=np.arange(1,5).reshape((1,4))
print(d)

print(d.shape)
print(d.ndim)
print("-"*50)
print(e)

print(e.shape)
print(e.ndim)

In [ ]:
d=np.arange(1,13).reshape((4,3))
e=np.arange(1,5).reshape((4,1))
print(d)

print(d.shape)
print(d.ndim)
print("-"*50)
print(e)

print(e.shape)
print(e.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
2
--------------------------------------------------
[[1]
 [2]
 [3]
 [4]]
(4, 1)
2


In [ ]:
np.concatenate([d,e],axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

In [ ]:
np.concatenate([d,e],axis=1)

array([[ 1,  2,  3,  1],
       [ 4,  5,  6,  2],
       [ 7,  8,  9,  3],
       [10, 11, 12,  4]])

In [ ]:
# stacking

In [ ]:
d=np.arange(1,5)
e=np.arange(1,5)
print(d)
print(d.shape)
print(d.ndim)
print("-"*50)
print(e)

print(e.shape)
print(e.ndim)

[1 2 3 4]
(4,)
1
--------------------------------------------------
[1 2 3 4]
(4,)
1


In [ ]:
np.hstack([d,e])

array([1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
np.vstack([d,e])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
d=np.arange(1,5).reshape((1,4))
e=np.arange(1,5).reshape((1,4))
print(d)
print(d.shape)
print(d.ndim)
print("-"*50)
print(e)

print(e.shape)
print(e.ndim)

[[1 2 3 4]]
(1, 4)
2
--------------------------------------------------
[[1 2 3 4]]
(1, 4)
2


In [ ]:
np.hstack([d,e])

array([[1, 2, 3, 4, 1, 2, 3, 4]])

In [ ]:
np.vstack([d,e])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
# 2D arrays with m rows and n columns
d=np.arange(1,13).reshape((3,4))
e=np.arange(2,14).reshape((3,4))
print(d)
print(d.shape)
print(d.ndim)
print("-"*50)
print(e)

print(e.shape)
print(e.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
--------------------------------------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
(3, 4)
2


In [ ]:
np.hstack([d,e])

array([[ 1,  2,  3,  4,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 10, 11, 12, 13]])

In [ ]:
np.vstack([d,e])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
d=np.arange(1,13).reshape((3,4))
e=np.arange(1,5)
print(d)
print(d.shape)
print(d.ndim)
print("-"*50)
print(e)

print(e.shape)
print(e.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
--------------------------------------------------
[1 2 3 4]
(4,)
1


In [ ]:
np.hstack([d,e])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
np.vstack([d,e])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
d=np.arange(1,13).reshape((3,4))
e=np.arange(1,4).reshape((3,1))
print(d)
print(d.shape)
print(d.ndim)
print("-"*50)
print(e)

print(e.shape)
print(e.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
--------------------------------------------------
[[1]
 [2]
 [3]]
(3, 1)
2


In [ ]:
np.hstack([d,e])

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  2],
       [ 9, 10, 11, 12,  3]])

In [ ]:
np.vstack([d,e])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 1

In [ ]:
d=np.arange(1,13).reshape((3,4))
e=np.arange(1,5).reshape((1,4))
print(d)
print(d.shape)
print(d.ndim)
print("-"*50)
print(e)

print(e.shape)
print(e.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
--------------------------------------------------
[[1 2 3 4]]
(1, 4)
2


In [ ]:
np.hstack([d,e])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [ ]:
np.vstack([d,e])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
d=np.arange(1,13).reshape((3,4))
e=np.arange(1,11).reshape((2,5))
print(d)
print(d.shape)
print(d.ndim)
print("-"*50)
print(e)

print(e.shape)
print(e.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
--------------------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
2


In [ ]:
np.hstack([d,e])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
np.vstack([d,e])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 5

In [ ]:
#Splitting
import numpy as np

In [ ]:
d=np.arange(1,13)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
np.split(d,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [ ]:
np.split(d,5)


ValueError: array split does not result in an equal division

In [ ]:
np.split(d,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [ ]:
np.split(d,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [ ]:
np.split(d,6)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

In [ ]:
np.split(d,13)

ValueError: array split does not result in an equal division

In [ ]:
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
np.split(d,[5])

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11, 12])]

In [ ]:
np.split(d,[5,7])

[array([1, 2, 3, 4, 5]), array([6, 7]), array([ 8,  9, 10, 11, 12])]

In [ ]:
np.split(d,[5,7,10])

[array([1, 2, 3, 4, 5]), array([6, 7]), array([ 8,  9, 10]), array([11, 12])]

In [ ]:
np.split(d,[5,7,13])

[array([1, 2, 3, 4, 5]),
 array([6, 7]),
 array([ 8,  9, 10, 11, 12]),
 array([], dtype=int64)]

In [ ]:
np.split(d,[-5,-4])

[array([1, 2, 3, 4, 5, 6, 7]), array([8]), array([ 9, 10, 11, 12])]

In [ ]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.split(d,[2,10,6])

[array([1, 2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10]),
 array([], dtype=int64),
 array([ 7,  8,  9, 10, 11, 12])]

In [ ]:
np.split(d,[-5,-9])

[array([1, 2, 3, 4, 5, 6, 7]),
 array([], dtype=int64),
 array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])]

In [ ]:
d=np.arange(1,13).reshape((1,12))
print(d)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [ ]:
np.split(d,2,axis=1)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

In [ ]:
np.hsplit(d,2)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

In [ ]:
np.split(d,2,axis=0)

ValueError: array split does not result in an equal division

In [ ]:
d=np.arange(1,13).reshape((3,4))
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
np.split(d,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [ ]:
np.split(d,2,axis=0)

ValueError: array split does not result in an equal division

In [ ]:
np.split(d,3,axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [ ]:
np.hsplit(d,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [ ]:
np.vsplit(d,3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [ ]:
np.split(d,[1sss],axis=1)

[array([[1],
        [5],
        [9]]),
 array([[ 2,  3,  4],
        [ 6,  7,  8],
        [10, 11, 12]])]

In [ ]:
np.split(d,[1,2],axis=1)

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [ ]:
np.split(d,[1],axis=0)

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])]

In [ ]:
np.hsplit(d,[1,2])

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [ ]:
np.vsplit(d,[1,2])

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [ ]:
a = np.array([0,1,2,3,4,5])
b = a[a%1 == 0]

b[0] = 10

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
# print(a)
# print(b)
# print(b.T)
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
a = np.array([[1], [2], [3]])
print(a)
print(a.shape)
b = np.array([[4], [5], [6]])
print("-"*50)
print(b)
np.vstack((a, b))

[[1]
 [2]
 [3]]
(3, 1)
--------------------------------------------------
[[4]
 [5]
 [6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.hstack((a, b)))

[1 2 3 4 5 6]


In [ ]:
# Broadcasting 

# Broadcasting

## Rules

### For each dimension ( going from right side)
#### 1. The size of each dimension should be same OR
#### 2. The size of one dimension should be 1


##### Rule 1 : If two array differ in the number of dimensions, the shape of one with fewer dimensions is padded with ones on its leading( Left Side).
##### Rule 2 : If the shape of two arrays doesnt match in any dimensions, the array with shape equal to 1 is stretched to match the other shape.
##### Rule 3 : If in any dimesion the sizes disagree and neither equal to 1 , then Error is raised.


In [ ]:
a=np.arange(1,5)
a+2

NameError: ignored

In [ ]:
b=np.arange(1,7).reshape((3,2))
c=np.arange(1,3)

print(b)
print(b.shape)
print(b.ndim)
print("-"*50)
print(c)
print(c.shape)
print(c.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2
--------------------------------------------------
[1 2]
(2,)
1


In [ ]:
b+c

array([[2, 4],
       [4, 6],
       [6, 8]])

In [ ]:
d=np.arange(1,4)
print(d)

[1 2 3]


In [ ]:
b+d

ValueError: ignored

In [ ]:
a=np.arange(1,7).reshape((3,2))
b=np.array([10,20,30,40]).reshape((2,2))
print(a)
print(b)

[[1 2]
 [3 4]
 [5 6]]
[[10 20]
 [30 40]]


In [ ]:
a+b

ValueError: ignored

In [ ]:
a=np.array([[1,2,3]])
b=np.array([[10],[20],[30]])
print(a)
print(a.shape)
print(a.ndim)
print("-"*50)
print(b)
print(b.shape)
print(b.ndim)

In [ ]:
a+b

In [ ]:
a=np.arange(1,5).reshape((1,4))
b=np.arange(1,6).reshape((5,1))
print(a)
print(a.shape)
print(a.ndim)
print("-"*50)
print(b)
print(b.shape)
print(b.ndim)

In [ ]:
a+b

In [ ]:
a=np.arange(1,9).reshape((2,4))
b=np.arange(1,6).reshape((5,1))
print(a)
print(a.shape)
print(a.ndim)
print("-"*50)
print(b)
print(b.shape)
print(b.ndim)

In [ ]:
a+b

In [ ]:
a=np.arange(1,7).reshape((3,2))
b=np.arange(1,13).reshape((6,2))
print(a)
print(a.shape)
print(a.ndim)
print("-"*50)
print(b)
print(b.shape)
print(b.ndim)

In [ ]:
a+b

![Broadcasting.png](attachment:Broadcasting.png)


In [ ]:
A = np.arange(12).reshape(3, 4)
B = np.array([1, 2, 3])

In [ ]:
A+B

In [ ]:
(2,1) & (1,3)

In [ ]:
a=np.arange(1,3).reshape((2,1))
b=np.arange(1,4).reshape((1,3))
print(a)
print(a.shape)
print(a.ndim)
print("-"*50)
print(b)
print(b.shape)
print(b.ndim)

In [ ]:
a+b

In [ ]:
a=np.array([4,2,31,15])
b=np.array([2,4,15,31])
c=np.array([1,0,3,2])
d=np.array([8,5,2,7])

In [ ]:
d[[1,0,3,2]]

In [ ]:
a=np.array([[23,54,76],[76,45,12],[56,87,90]])
a

In [ ]:
a.flatten()

In [ ]:
np.sort()