In [ ]:
import numpy as np

In [ ]:
a=[1,2,3,4,5]
print([i**2 for i in a])

[1, 4, 9, 16, 25]


In [ ]:
# we can create numpy arrays using np.array
b=np.array([1,2,3,4,5])
print(b**2)

[ 1  4  9 16 25]


In [ ]:
# numpy supports elementwise operations
print(b+2)

[3 4 5 6 7]


In [ ]:
c=np.array(a)
print(c)

[1 2 3 4 5]


In [ ]:
# type of the entire Numpy array
type(a)

list

In [ ]:
type(b)

numpy.ndarray

In [ ]:
l=range(10000)


In [ ]:
%timeit [i**2 for i in l]

2.51 ms ± 46.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
m=np.arange(10000)
print(m)

[   0    1    2 ... 9997 9998 9999]


In [ ]:
%timeit m**2

3.59 µs ± 32.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
c=np.array([1,2,3])
print(type(c))
# data type of elements of the numpy array
c.dtype

<class 'numpy.ndarray'>


dtype('int64')

In [ ]:
# because of one element 4.5 , every element's dtype has been type casted into float
c=np.array([1,2,3,4.5])
print(type(c))
print(c)
c.dtype

<class 'numpy.ndarray'>
[1.  2.  3.  4.5]


dtype('float64')

In [ ]:
# because of one element 4.5 , every element's dtype has been type casted into string
c=np.array([1,2,3,"c"])
print(type(c))
print(c)
c.dtype

<class 'numpy.ndarray'>
['1' '2' '3' 'c']


dtype('<U21')

In [ ]:
c=np.array([1,2,3,"4.5",3.9])
print(type(c))
print(c)
c.dtype

<class 'numpy.ndarray'>
['1' '2' '3' '4.5' '3.9']


dtype('<U32')

In [ ]:
# booleans are treated as 1 and 0 for True and False respectively
c=np.array([1,1,0,True,False])
print(type(c))
print(c)
c.dtype

<class 'numpy.ndarray'>
[1 1 0 1 0]


dtype('int64')

In [ ]:
b=np.array([1,2,3,4,5])
# used to find out the dimension of the array
b.ndim

1

In [ ]:
# used to find out the shape of the numpy array
b.shape

(5,)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

In [ ]:
# range function generates numbers for start to end(excluded) with some step size
# range( start, stop,step_size)
f=range(0,10,1)
print(f)

range(0, 10)


In [ ]:
# arange function in numpy generates numbers for start to end(excluded) with some step size
# arange( start, stop,step_size)
# arange is different from range --> we can give floats as step size
g=np.arange(0,10,0.67)
print(g)

[0.   0.67 1.34 2.01 2.68 3.35 4.02 4.69 5.36 6.03 6.7  7.37 8.04 8.71
 9.38]


In [ ]:
# linspace is used to create equally spaced numbers between start and end both included.
start,end,flag_count=0,100,25
np.linspace(start,end,flag_counts)

array([  0.        ,   4.16666667,   8.33333333,  12.5       ,
        16.66666667,  20.83333333,  25.        ,  29.16666667,
        33.33333333,  37.5       ,  41.66666667,  45.83333333,
        50.        ,  54.16666667,  58.33333333,  62.5       ,
        66.66666667,  70.83333333,  75.        ,  79.16666667,
        83.33333333,  87.5       ,  91.66666667,  95.83333333,
       100.        ])

In [ ]:
f=np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
# creating a 2d numpy Array
m=np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
m.shape

(2, 3)

In [ ]:
m.ndim

2

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
len(a)

8

In [ ]:
len(m)

2

In [ ]:
m2=np.arange(1,13)
m2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
m2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# here we knew that we want 2 rows, but not the columns, so we passed -1 as the parameter. 
# numpy will automatically find out the required number of columns it need to display the data.
m2.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
m2.reshape(-1,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# we need to pass atleast one dimension
m2.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [ ]:
m2.reshape(5,-1)

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [ ]:
m2=np.arange(1,13)
#reshape functions reshapes the arrays into the shape of (rows and columns) we define
m2=m2.reshape(3,4)


In [ ]:
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
m3=np.arange(1,14)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
m3.reshape(3,4)

ValueError: cannot reshape array of size 13 into shape (3,4)

In [ ]:
import numpy as np
m4=np.array([[1,2,3],[4,5,6,8,0,9]])
print(m4)

[list([1, 2, 3]) list([4, 5, 6, 8, 0, 9])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [ ]:
m3=np.arange(1,14)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
m3.reshape(1,13)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [ ]:
m3.reshape(13,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [ ]:
m3.reshape(2,-1)

ValueError: cannot reshape array of size 13 into shape (2,newaxis)

In [ ]:

a = np.arange(1,17).reshape(-1,2)
a.shape

In [ ]:

a = np.arange(1,17).reshape(-1,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
m4=np.arange(1,7)
m4

array([1, 2, 3, 4, 5, 6])

In [ ]:
m5=m4.reshape(2,3)
print(m5)

[[1 2 3]
 [4 5 6]]


In [ ]:
m5.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
m4=np.arange(1,13).reshape(6,2)
print(m4)
# .T creates a transpose of a matrix rows--> columns, columns--> rows
# converting rows into columns.
m4.T

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [ ]:
m5=np.arange(3).reshape(1,3)
m5.ndim

2

In [ ]:
m5.shape

(1, 3)

In [ ]:
m5.T.shape

(3, 1)

In [ ]:
m6=np.array([1,2,3])
m6.shape

(3,)

In [ ]:
m6.ndim

1

In [ ]:
m6.T

array([1, 2, 3])

In [ ]:
m6=np.array([[1,2,3]])
m6.shape

(1, 3)

In [ ]:
m6.ndim

2

In [ ]:
m6.T

array([[1],
       [2],
       [3]])

In [ ]:
m7=np.arange(1,13).reshape(3,4)
m7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m7.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# creating special arrays

In [ ]:
# creating 1D array with all the values as 0
np.zeros(3)

array([0., 0., 0.])

In [ ]:
# creating 2D array  of shape (3,3) with all the values as 0
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# creating 2D array  of shape (3,) with all the values as 1

np.ones(3)

array([1., 1., 1.])

In [ ]:
# creating 2D array  of shape (6,2) with all the values as 1
np.ones((6,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a*2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
a=np.ones((3,3),dtype=np.int32)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
# creating 2D array  of shape (3,3) with all the values as 4.0
np.full((3,3),4.0)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [ ]:
# creating 2D array  of shape (3,3) with values at main diagonal as 1 and rest as 0
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# creating 2D array  of shape (3,3) with values at main diagonal as 1 and rest as 0
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# creating 2D array  of shape (3,3) with values at main diagonal as 1,2,3 and rest as 0
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
#indexing

In [ ]:
m1=np.arange(3,10)
m1

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#accessing the data
m1[0]

3

In [ ]:
m1[1]

4

In [ ]:
# we can access using negative indexes
m1[-1]

9

In [ ]:
m1[-2]

8

In [ ]:
m1[-7]

3

In [ ]:
m2=np.arange(1,13).reshape(3,4)
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# method - 1, for accessing elements
m2[1][1]

6

In [ ]:
# method - 2, for accessing elements ( Preferred )
m2[1,1]

6

In [ ]:
m7=np.array([100,100,300,400,500,600])
m7

array([100, 100, 300, 400, 500, 600])

In [ ]:
# We can pass a list of indexes of the elements we want to access 
m7[[2,4,5,4]]

array([300, 500, 600, 500])

In [ ]:
m2=np.arange(1,13).reshape(3,4)
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# to access multiple elements, we need to pass the row and column indexes separately in lists.
m2[[1,1,2],[1,3,3]]

array([ 6,  8, 12])

In [ ]:
# we cannot pass each elements separately.
# m2[[1,1],[1,3],[2,3]]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [ ]:
m8=np.arange(1,13)

In [ ]:
m8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# slicing elements from a numpy array.
m8[:5]

array([1, 2, 3, 4, 5])

In [ ]:
m8[7:]

array([ 8,  9, 10, 11, 12])

In [ ]:
# slicing elements from a numpy array using step size
m8[1::2]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
m8[1::3]

array([ 2,  5,  8, 11])

In [ ]:
# we can pass negative step sizes as well
m8[-11:-5]

array([2, 3, 4, 5, 6, 7])

In [ ]:
m8[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
m8[2:5:-1]

array([], dtype=int64)

In [ ]:
m8[5:2:-1]

array([6, 5, 4])

In [ ]:
m9=np.arange(1,13).reshape(3,4)

In [ ]:
m9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m9[0]

array([1, 2, 3, 4])

In [ ]:
m9[0][1:3]

array([2, 3])

In [ ]:
# accessing 0th indexed row and columns of indexes 1 and 2
m9[0,1:3]

array([2, 3])

In [ ]:

# slicing multiple rows and columns
m9[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
m9[1:,:2]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
m9[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [ ]:
# if we want to access specific columns of rows, we pass the index within a list or tuple. both works
# m9[:,[0,1,2]] it also works the same way

m9[:,(0,1,2)]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
a[2 : ] = b[ : : -1]


In [ ]:
a = [1,2,3,4,5]

In [ ]:
b = [8,7,6]

In [ ]:
a[2 : ] = b[ : : -1]

In [ ]:
a

[1, 2, 6, 7, 8]

In [ ]:
a[3]=100

In [ ]:
a

[1, 2, 6, 100, 8]

In [ ]:
m1 = np.array([[0,1,2,3],
[4,5,6,7],
[8,9,10,11]])

m1[0,1:3]

array([1, 2])

In [ ]:
a = np.array([0,1,2,3,4,5])
a[4:]=10
a

array([ 0,  1,  2,  3, 10, 10])

In [ ]:
m1=np.arange(1,13).reshape(3,4)
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# numpy also supports elements logical operations.
# here we are creating mask of boolean values.
mask=m1<6
mask

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [ ]:
m1[mask]

array([1, 2, 3, 4, 5])

In [ ]:
# filtering out the values that satisfies the condition or the values where we have True as value.
m1[m1%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
# creating multiple conditions.
mask=(m1%2==0)|(m1%5==0) 

In [ ]:
mask

array([[False,  True, False,  True],
       [ True,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
m1[mask]

array([ 2,  4,  5,  6,  8, 10, 12])

In [ ]:
m1%2==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
m1%5==0

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True, False, False]])

In [ ]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
mask
a[mask] = -1
# What'll be the values of a?

In [ ]:
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
np.eye?

In [ ]:
np.eye(10,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])